project_id = "wlustbjdqwemnqtyilxp"

[functions.fetch-crypto-data]
verify_jwt = false

[functions.fetch-news]
verify_jwt = false

[functions.check-alerts]
verify_jwt = false

[functions.scheduler]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.admin-promo]
verify_jwt = false
