project_id = "wlustbjdqwemnqtyilxp"

[functions.fetch-crypto-data]
verify_jwt = false

[functions.fetch-news]
verify_jwt = false

[functions.check-alerts]
verify_jwt = false

[functions.scheduler]
verify_jwt = false
