project_id = "wlustbjdqwemnqtyilxp"

[functions.market-recap]
verify_jwt = false

[functions.track-analytics]
verify_jwt = false

[functions.fetch-stock-data]
verify_jwt = false

[functions.fetch-forex-data]
verify_jwt = false

[functions.fetch-commodity-data]
verify_jwt = false

[functions.fetch-index-data]
verify_jwt = false

[functions.fetch-macro-news]
verify_jwt = false

[functions.fetch-binance-klines]
verify_jwt = false

[functions.generate-daily-brief]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.nowpayments-webhook]
verify_jwt = false
