// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlustbjdqwemnqtyilxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsdXN0YmpkcXdlbW5xdHlpbHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NTAxOTMsImV4cCI6MjA4NzAyNjE5M30.TTcHFzR-MRHPGV8piY5vkF_nnViZ1ij2kqyg4JnDbwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});